### ISSUE TITLE
City Dashboard Mockups

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/carbondoomsday#4]
Design mockups based on moodboard for city indicators
Moodboard: https://projects.invisionapp.com/boards/QP3SKCXHT8S/

## Acceptance Criteria
* [ ] Designs have good UI/UX to facilitate experience and ease
* [ ] Designs have the chosen indicators
* [ ] Worked / refined on team feedback

**Comment by tanvirchahal** [comment]
Dashboard Dark - https://invis.io/GZQ7TLUS5TK
Dashboard Light - https://invis.io/9KQ7TR0M8HV

**Comment by anuveyatsu** [comment]
Issue moved to [datahq/cityindicators #1](https://github.com/datahq/cityindicators/issues/1) via [**ZenHub**](https://www.zenhub.com/)
